version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine

  julia_http_server:
    container_name: julia_http_server
    expose: 
      - 2000
    ports:
      - "8080:8080"
    image: knlod/simple_julia:latest
    networks: 
      - gateway

  julia_websocket_server:
    container_name: julia_websocket_server
    expose:
      - 2000
    ports:
      - "12346:12346"
    image: knlod/websockets_server
    networks:
      - gateway


networks:
  gateway: {}



